# Accent and UI colors
accent = "#7aa2f7"
active_border_color = "#7aa2f7"
active_tab_background = "#9ece6a"

# Cursor colors
cursor = "#c0caf5"

# Primary colors
foreground = "#c0caf5"
background = "#1a1b26"

# Selection colors
selection_foreground = "#1a1b26"
selection_background = "#9aa5ce"

# Normal colors (ANSI 0-7)
color0 = "#15161e"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#7aa2f7"
color5 = "#bb9af7"
color6 = "#7dcfff"
color7 = "#a9b1d6"

# Bright colors (ANSI 8-15)
color8  = "#414868"
color9  = "#ff899d"
color10 = "#9fe044"
color11 = "#faba4a"
color12 = "#8db0ff"
color13 = "#c7a9ff"
color14 = "#a4daff"
color15 = "#c0caf5"
